cask_args appdir: '/Applications'
tap 'homebrew/cask'

brew 'bash'
brew 'git'
brew 'vim'
brew 'coreutils'
brew 'imagemagick'
brew 'postgresql'
brew 'redis'
brew 'tree'
brew 'dfu-programmer'
brew 'zsh'

cask 'flux'
cask 'iterm2'
cask 'alfred'
cask 'caffeine'
cask 'spotify'
cask 'dropbox'
cask 'karabiner-elements'
cask 'stretchly'
